name: Request cleanup
on:
  issues:
    types:
      - labeled
jobs:
  delete:
    if: github.event.label.name == 'request'
    runs-on: ubuntu-latest
    steps:
      - name: Request cleanup
        run: gh issue delete "$NUMBER" --yes
        env:
          GH_TOKEN: ${{ secrets.SANITY_PAT }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
      - name: Ban user
        run: gh api --method PUT /user/blocks/$USERNAME
        env:
          GH_TOKEN: ${{ secrets.SANITY_PAT }}
          GH_REPO: ${{ github.repository }}
          USERNAME: ${{ github.event.issue.user.login }}